import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronDown, CircleCheck, Compass, Layers3, Sparkles, X } from 'lucide-react';
import type { Brief, Choice } from './types';
import { designs, features, goals, integrations, levels, pageOptions, plans, segments, siteTypes, steps } from './data/config';
import { calculatePrice, money } from './config/pricing';
import { submitBriefing } from './services/submitBriefing';

const blank: Brief = { client:{name:'',company:'',email:'',whatsapp:'',role:'',location:''}, business:{description:'',segment:'',audience:'',difference:''}, goals:[],websiteType:'institutional',pages:'medium',pageList:[],design:'Premium',theme:'Claro',features:['form'],seo:'pro',performance:'high',integrations:[],content:'client',hosting:'need',deadline:'1-2',plan:'pro' };
const Icon = ({children}:{children:React.ReactNode})=><span className="choice-icon">{children}</span>;
function ChoiceCard({item,selected,onClick,multi=false}: {item:Choice;selected:boolean;onClick:()=>void;multi?:boolean}) { return <button type="button" className={'choice '+(selected?'selected':'')} onClick={onClick} aria-pressed={selected}><span className="check">{selected&&<Check size={14}/>}</span>{item.tag&&<span className="tag">{item.tag}</span>}<strong>{item.title}</strong>{item.desc&&<small>{item.desc}</small>}{item.price !== undefined && item.price>0&&<em>+ {money(item.price)}</em>}{multi&&<span className="multi">{selected?'Incluído':'Adicionar'}</span>}</button> }
function Summary({brief,onClose}:{brief:Brief;onClose?:()=>void}) { const quote=calculatePrice(brief); const type=siteTypes.find(x=>x.id===brief.websiteType); return <aside className="summary"><div className="summary-head"><span>SEU PROJETO</span>{onClose&&<button onClick={onClose} aria-label="Fechar resumo"><X size={17}/></button>}</div><h3>{type?.title || 'Seu projeto digital'}</h3><p className="summary-note">Uma estimativa viva, baseada nas escolhas que você faz agora.</p><div className="quote-lines">{quote.items.map(([label,value])=><div key={label}><span>{label}</span><b>{money(value)}</b></div>)}</div><div className="total"><span>INVESTIMENTO ESTIMADO</span><strong>{money(quote.total)}</strong><small>Valores configuráveis · não inclui impostos</small></div><div className="recommend"><Sparkles size={16}/><div><b>Recomendação Atelier</b><p>{brief.websiteType==='ecommerce'?'Inclua performance premium para uma experiência de compra fluida.':'O pacote Pro equilibra estratégia, design e crescimento.'}</p></div></div></aside> }
function App() {
 const [brief,setBrief]=useState<Brief>(()=>{try{return {...blank,...JSON.parse(localStorage.getItem('atelier-brief')||'{}')}}catch{return blank}});
 const [screen,setScreen]=useState<'home'|'flow'|'success'>('home'); const [index,setIndex]=useState(0); const [openSummary,setOpenSummary]=useState(false); const [saved,setSaved]=useState(false); const [submitting,setSubmitting]=useState(false); const [submitError,setSubmitError]=useState('');
 useEffect(()=>{localStorage.setItem('atelier-brief',JSON.stringify(brief));setSaved(true);const id=setTimeout(()=>setSaved(false),1300);return()=>clearTimeout(id)},[brief]);
 const update=(patch:Partial<Brief>)=>setBrief(b=>({...b,...patch})); const step=steps[index]; const quote=useMemo(()=>calculatePrice(brief),[brief]);
 const toggle=(key:'goals'|'features'|'integrations', id:string)=>update({[key]:brief[key].includes(id)?brief[key].filter(x=>x!==id):[...brief[key],id]} as Partial<Brief>);
 const nav=(next:number)=>{setIndex(Math.max(0,Math.min(steps.length-1,next)));window.scrollTo({top:0,behavior:'smooth'})};
 const sendProject=async()=>{
   if (!brief.client.name.trim() || !brief.client.email.trim()) { setSubmitError('Informe seu nome e e-mail antes de enviar.'); setIndex(0); return; }
   setSubmitting(true); setSubmitError('');
   const submissionId=localStorage.getItem('atelier-submission-id') || crypto.randomUUID();
   localStorage.setItem('atelier-submission-id',submissionId);
   try { await submitBriefing(brief,submissionId); localStorage.removeItem('atelier-brief'); localStorage.removeItem('atelier-submission-id'); setScreen('success'); }
   catch (error) { setSubmitError(error instanceof Error ? error.message : 'Não foi possível enviar agora. Tente novamente.'); }
   finally { setSubmitting(false); }
 };
 const input=(label:string,value:string,onChange:(v:string)=>void,type='text')=><label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} /></label>;
 const renderStep=()=>{switch(step.id){
 case 'business': return <><section className="form-section"><div className="eyebrow">01 / CONTEXTO</div><h1>{step.title}</h1><p>{step.description}</p><div className="fields two">{input('Seu nome',brief.client.name,v=>setBrief(b=>({...b,client:{...b.client,name:v}})))}{input('Empresa',brief.client.company,v=>setBrief(b=>({...b,client:{...b.client,company:v}}))) }{input('E-mail',brief.client.email,v=>setBrief(b=>({...b,client:{...b.client,email:v}})),'email')}{input('WhatsApp',brief.client.whatsapp,v=>setBrief(b=>({...b,client:{...b.client,whatsapp:v}})))}</div><label className="field"><span>Qual é o seu segmento?</span><select value={brief.business.segment} onChange={e=>setBrief(b=>({...b,business:{...b.business,segment:e.target.value}}))}><option value="">Selecione o segmento</option>{segments.map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Conte um pouco sobre seu negócio</span><textarea value={brief.business.description} onChange={e=>setBrief(b=>({...b,business:{...b.business,description:e.target.value}}))} placeholder="O que sua empresa faz e por que ela existe?"/></label></section></>;
 case 'objective': return <section className="form-section"><div className="eyebrow">02 / DIREÇÃO</div><h1>{step.title}</h1><p>{step.description}</p><div className="grid cards">{goals.map(x=><ChoiceCard key={x.id} item={x} selected={brief.goals.includes(x.id)} onClick={()=>toggle('goals',x.id)} multi/>)}</div></section>;
 case 'structure': return <section className="form-section"><div className="eyebrow">03 / ARQUITETURA</div><h1>Uma estrutura feita para crescer.</h1><p>Escolha o tipo de experiência e a profundidade de conteúdo desejada.</p><h2>Qual formato combina com seu projeto?</h2><div className="grid site-types">{siteTypes.map(x=><ChoiceCard key={x.id} item={x} selected={brief.websiteType===x.id} onClick={()=>update({websiteType:x.id})}/>)}</div><h2>Quantidade aproximada de páginas</h2><div className="grid pages">{pageOptions.map(x=><ChoiceCard key={x.id} item={x} selected={brief.pages===x.id} onClick={()=>update({pages:x.id})}/>)}</div></section>;
 case 'design': return <section className="form-section"><div className="eyebrow">04 / IDENTIDADE</div><h1>{step.title}</h1><p>{step.description}</p><div className="grid styles">{designs.map((x,i)=><ChoiceCard key={x.id} item={x} selected={brief.design===x.id} onClick={()=>update({design:x.id})}/>)}</div><div className="preference"><div><span>ATMOSFERA</span><b>Qual será o tom da experiência?</b></div><div className="toggle"><button className={brief.theme==='Claro'?'active':''} onClick={()=>update({theme:'Claro'})}>Claro</button><button className={brief.theme==='Escuro'?'active':''} onClick={()=>update({theme:'Escuro'})}>Escuro</button></div></div></section>;
 case 'features': return <section className="form-section"><div className="eyebrow">05 / CAPACIDADES</div><h1>{step.title}</h1><p>{step.description}</p><div className="grid feature-grid">{features.map(x=><ChoiceCard key={x.id} item={x} selected={brief.features.includes(x.id)} onClick={()=>toggle('features',x.id)} multi/>)}</div></section>;
 case 'strategy': return <section className="form-section"><div className="eyebrow">06 / CRESCIMENTO</div><h1>Prepare o terreno para performar.</h1><p>Selecione o nível de alcance, velocidade e conexão necessário.</p><h2>SEO</h2><div className="grid levels">{levels.seo.map(x=><ChoiceCard key={x.id} item={x} selected={brief.seo===x.id} onClick={()=>update({seo:x.id})}/>)}</div><h2>Performance</h2><div className="grid levels">{levels.performance.map(x=><ChoiceCard key={x.id} item={x} selected={brief.performance===x.id} onClick={()=>update({performance:x.id})}/>)}</div><h2>Integrações</h2><div className="pills">{integrations.map(x=><button key={x.id} onClick={()=>toggle('integrations',x.id)} className={brief.integrations.includes(x.id)?'active':''}>{brief.integrations.includes(x.id)&&<Check size={14}/>} {x.title}<small>{x.price&&` +${money(x.price)}`}</small></button>)}</div></section>;
 case 'investment': return <section className="form-section"><div className="eyebrow">07 / PARCERIA</div><h1>Escolha como vamos construir juntos.</h1><p>Todos os pacotes partem do seu briefing e incluem um processo humano, próximo e transparente.</p><div className="plans">{plans.map(x=><ChoiceCard key={x.id} item={x} selected={brief.plan===x.id} onClick={()=>update({plan:x.id})}/>)}</div><div className="timeline"><span>LANÇAMENTO DESEJADO</span>{[['asap','O quanto antes'],['2-4','2–4 semanas'],['1-2','1–2 meses'],['2-3','2–3 meses'],['flexible','Sem urgência']].map(([id,label])=><button className={brief.deadline===id?'active':''} onClick={()=>update({deadline:id})} key={id}>{label}{id==='asap'&&<small> + prioridade</small>}</button>)}</div></section>;
 default:return <section className="form-section review"><div className="eyebrow">08 / PROPOSTA</div><h1>{step.title}</h1><p>{step.description}</p><div className="review-grid"><div><span>CLIENTE</span><b>{brief.client.name || 'Seu nome'} · {brief.client.company || 'Sua empresa'}</b></div><div><span>FORMATO</span><b>{siteTypes.find(x=>x.id===brief.websiteType)?.title}</b></div><div><span>OBJETIVOS</span><b>{brief.goals.join(', ') || 'A definir'}</b></div><div><span>DESIGN</span><b>{brief.design} · tema {brief.theme.toLowerCase()}</b></div><div><span>RECURSOS</span><b>{brief.features.length} funcionalidades selecionadas</b></div><div><span>ESTRATÉGIA</span><b>SEO {brief.seo} · Performance {brief.performance}</b></div></div><div className="final-price"><span>INVESTIMENTO ESTIMADO</span><strong>{money(quote.total)}</strong><p>O próximo passo é receber uma proposta personalizada, sem compromisso.</p></div></section>}}
 if(screen==='home') return <main className="home"><nav><a className="brand"><span>✦</span> atelier<span>.</span></a><button className="ghost" onClick={()=>setScreen('flow')}>Acessar briefing <ArrowRight size={16}/></button></nav><section className="hero"><div className="hero-copy"><div className="pill"><Sparkles size={14}/> BRIEFING INTELIGENTE</div><h1>Seu próximo site <i>começa aqui.</i></h1><p>Uma experiência guiada para transformar a ambição da sua marca em um projeto digital claro, estratégico e pronto para acontecer.</p><button className="primary big" onClick={()=>setScreen('flow')}>Começar meu projeto <ArrowRight size={18}/></button><div className="hero-meta"><span><CircleCheck size={17}/> 10–15 min</span><span><CircleCheck size={17}/> orçamento em tempo real</span></div></div><div className="orbital"><div className="orbit-label top">BRIEFING <b>01</b></div><div className="orbit-label right">ESTRATÉGIA <b>02</b></div><div className="orbit-label bottom">DESIGN <b>03</b></div><div className="orb-core"><Compass size={42}/><span>do insight<br/>ao impacto</span></div><div className="orbit-dot d1"/><div className="orbit-dot d2"/><div className="orbit-dot d3"/></div></section><section className="how"><span className="eyebrow">O PROCESSO ATELIER</span><h2>Clareza em cada decisão.<br/><i>Excelência em cada detalhe.</i></h2><div className="how-grid">{['Você nos conta sobre sua marca','Definimos a experiência ideal','Componha seu investimento','Receba uma proposta estratégica'].map((x,i)=><div key={x}><span>0{i+1}</span><b>{x}</b><p>Uma etapa pensada para revelar o que realmente importa.</p></div>)}</div></section></main>;
 if(screen==='success') return <main className="success"><div className="success-mark">✦</div><div className="pill">PROJETO RECEBIDO</div><h1>Está nas mãos certas.</h1><p>Recebemos seu briefing e vamos analisar cada detalhe para preparar uma proposta à altura da sua visão.</p><div className="next"><span>PRÓXIMOS PASSOS</span><b>01 · Análise estratégica</b><b>02 · Proposta personalizada</b><b>03 · Conversa de alinhamento</b></div><button className="primary" onClick={()=>setScreen('home')}>Voltar ao início</button></main>;
 return <main className="app"><header className="topbar"><button className="brand bare" onClick={()=>setScreen('home')}><span>✦</span> atelier<span>.</span></button><div className="progress"><span>{String(index+1).padStart(2,'0')} / {String(steps.length).padStart(2,'0')}</span><div><i style={{width:`${((index+1)/steps.length)*100}%`}}/></div><b>{step.label}</b></div><span className="saved">{saved?'Salvo agora':'Salvo automaticamente'}</span></header><div className="stepper">{steps.map((s,i)=><button onClick={()=>nav(i)} className={i===index?'current':i<index?'done':''} key={s.id}><span>{i<index?<Check size={13}/>:String(i+1).padStart(2,'0')}</span>{s.label}</button>)}</div><div className="workspace"><div className="stage">{renderStep()}<footer className="actions"><button className="back" disabled={index===0} onClick={()=>nav(index-1)}><ArrowLeft size={17}/> Voltar</button>{index<steps.length-1?<button className="primary" onClick={()=>nav(index+1)}>Continuar <ArrowRight size={17}/></button>:<button className="primary" disabled={submitting} onClick={sendProject}>{submitting?'Enviando projeto…':'Solicitar proposta'} <ArrowRight size={17}/></button>}</footer></div><Summary brief={brief}/></div><button className="summary-button" onClick={()=>setOpenSummary(true)}><Layers3 size={17}/> Ver resumo <b>{money(quote.total)}</b></button>{openSummary&&<div className="sheet"><Summary brief={brief} onClose={()=>setOpenSummary(false)}/></div>}{submitError&&<p className="submit-error" role="alert">{submitError}</p>}</main>
}
export default App;
